### ISSUE TITLE
Glitchy on Firefox Mobile

### ISSUE THREAD

**Issue by sole** [x-tag/shiftbox#1]
The transition is glitchy in Firefox Mobile (both stable and nightly), showing the entire content of the section layer during the transition instead of cropping it.

It works fine on desktop Firefox, FFOS simulator and Chrome mobile.

Test case (it's actually the current shiftbox demo):
http://people.mozilla.org/~spenades/test_cases/shiftbox_glitch/demo/

**Comment by pennyfx** [comment]
Fixed.  Had to set an initial transition of 0 to both aside and section.
