### ISSUE TITLE
Fixes and optimizations for shiftbox

### ISSUE THREAD

**Issue by csuwildcat** [x-tag/shiftbox#2]
1) Should use delegation: https://github.com/x-tag/shiftbox/blob/master/src/shiftbox.js#L14

2) No need for data- attribute prefix use, but if you do, don't mixed case attributes are not desired. Mixed case attributes are not preserved in HTML and setAttribute pays no attention, it's just cruft: https://github.com/x-tag/shiftbox/blob/master/src/shiftbox.js#L37

3) Why are we using an attribute and a variable to track state?: https://github.com/x-tag/shiftbox/blob/master/src/shiftbox.js#L16

**Comment by pennyfx** [comment]
Fixed
